:example:
  :__record_element: "record"
  :author: "author"
  :title:
    :elements:
      - "title/main"
      - "title/subtitle"
    :string: "%s: %s"
    :empty: ">>n/a<<"
  :place:
    :elements:
      - "city"
      - "country"
    :separator: " / "
:sisis-ex:
  :__record_element: "0000"  # KatalogNr
  :author:
    :elements:
      - "0100"               # VerfAnsetz
      - "0101"               # Verf_Ordn
    :string: "%s (%s)"
  :title:
    :elements:
      - "0331"               # HST
      - "0335"               # HSTZusatz
      - "0370"               # Untertitstab
    :string: "%s : %s [%s]"
  :place: "2028"             # ort2sb
:multiple-fields-per-element:
  :__record_element: "record"
  :author:
    :elements:
      - "author"
      - "city"
      - "title/main"
    :string: "%s (%s) [%s]"
  :title:
    :elements:
      - "title/main"
      - "title/subtitle"
      - "author"
    :string: "%s: %s (%s)"
    :empty: ">>n/a<<"
  :place:
    :elements:
      - "city"
      - "country"
    :separator: " / "
:sisis-multiple-fields-per-element:
  :__record_element: "0000"
  :author:
    :elements:
      - "0100"
      - "0101"
      - "0331"
      - "2028"
    :string: "VerfAnsetz=%s (Verf_Ordn=%s) [HST=%s] / ort2sb=%s"
  :title:
    :elements:
      - "0331"
      - "0335"
      - "0370"
      - "0100"
    :string: "HST=%s : HSTZusatz=%s [Untertitstab=%s] (VerfAnsetz=%s)"
  :place:
    :elements:
      - "2028"
      - "0335"
      - "0370"
      - "0100"
    :string: "ort2sb=%s (HSTZusatz=%s [Untertitstab=%s] / VerfAnsetz=%s)"
