:example:
  :__record_element: "record"
  :author:
    :elements:
      - "author"
      - "title/main"
    :string: "AU=%s TI=%s"
  :title:
    :elements:
      - "title/main"
      - "title/subtitle"
      - "author"
      - "country"
    :string: "%s: %s / %s (%s)"
    :empty: ">>n/a<<"
  :place:
    :elements:
      - "city"
      - "country"
    :separator: " / "
