:example:
  :record_element: "record"
  :author:
    :element: "author"
    :string: "AU=%s"
  :title:
    :elements:
      - "title/main"
      - "title/subtitle"
    :string: "%s: %s"
    :empty: ">>n/a<<"
  :place:
    :elements:
      - "city"
      - "country"
    :separator: " / "
