:example:
  :record_element: "record"
  :author: "author"
  :title:
    :elements:
      - "title/main"
      - "title/subtitle"
    :string: "%s: %s"
    :empty: ">>n/a<<"
  :place:
    - "city"
    - "country"
